FROM dockerfile/ubuntu

# Startup script
CMD ["/bin/bash"]

# Define mount points.
VOLUME ["/data/complete", "/data/pending"]

# Install dependancies
# RUN apt-get update \
#     && apt-get install -y \
#         git \
#     && rm -rf /var/lib/apt/lists/*
