Wowza:
  image: wowzamedia/wowza-streaming-engine-linux:4.7.1
  entrypoint: /sbin/entrypoint.sh
  ports:
    - "1935:1935"
    - "8086:8086"
    - "8087:8087"
    - "8088:8088"
    - "443:443"
  volumes:
    - /opt/wowza/conf:/usr/local/WowzaStreamingEngine/conf
    - /opt/wowza/applications:/usr/local/WowzaStreamingEngine/applications
    - /opt/wowza/lib:/usr/local/WowzaStreamingEngine/lib
    - /opt/wowza/content:/usr/local/WowzaStreamingEngine/content
    - /opt/wowza/logs/wowza:/usr/local/WowzaStreamingEngine/logs
    - /opt/wowza/logs/manager:/usr/local/WowzaStreamingEngine/manager/logs
    - /opt/wowza/logs/supervisor:/supervisor/supervisord.log
