piwik:
    build: ../piwik
    ports:
        - "80:80"
    links:
        - mysql
    restart: always

mysql:
    image: mysql:latest
    ports:
        - "3307:3306"
    environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=piwik
    restart: always