# Data Containers

tmpdata:
  image: busybox:latest
  volumes:
    - /tmp
    - /home/.cos


# Service Containers

rabbitmq:
  image: rabbitmq:latest


# Server Containers

web:
  build: .
  command: 'invoke server'
  environment:
    - SOURCE_BRANCH=develop
    - SOURCE_REPO=https://github.com/CenterForOpenScience/waterbutler
  ports:
    - 7777:7777
  expose:
    - 7777
  links:
    - rabbitmq:rabbitmq
  volumes_from:
    - tmpdata

celery:
  build: .
  command: 'invoke celery'
  environment:
    - SOURCE_BRANCH=develop
    - SOURCE_REPO=https://github.com/CenterForOpenScience/waterbutler
  links:
    - rabbitmq:rabbitmq
  volumes_from:
    - tmpdata
